anon_menu_section:
  type: string
  default: "anon-menu"
  description:
    en: "Custom section to show for only for anonymous (not-logged-in) users. Use all lowercase and dashes for spaces (ie: Anon Menu = anon-menu)."

user_menu_section:
  type: string
  default: "user-menu"
  description:
    en: "Custom section to show for logged-in users only. Use all lowercase and dashes for spaces (ie: User Menu = user-menu)."
